spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shixun?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    pathmatch:
      use-suffix-pattern: true
redis:
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
mybatis:
  mapper-locations: classpath:mappers/*.xml

